# Generated by Django 4.2.2 on 2023-06-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='data',
            field=models.JSONField(),
        ),
    ]
