# Generated by Django 4.2.2 on 2023-06-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_event_data_alter_participant_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
