# Generated by Django 4.2.2 on 2023-07-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_event_event_name_event_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
