# Generated by Django 4.2.2 on 2023-07-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_event_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
